name: Download and Merge Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create download directory
      run: mkdir -p download

    - name: Download files
      run: |
        links=(
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/openai"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/bing"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/twitter"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/reddit"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/4chan"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/pornhub"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/meta"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/facebook"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/instagram"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/messenger"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/threads"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/whatsapp"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/youtube"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/yandex"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/google"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/bbc"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/bloomberg"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/theguardian"
          "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/category-porn"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/nyaa"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/1337x"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/btdig"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/demonoid"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/piratebay"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/rarbg"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/mega"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/imgur"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/gfycat"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/18comic"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/54647"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/anon-v"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/avmoo"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/bdsmhub"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/bilibili2"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/boboporn"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/bongacams"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/boylove"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/bttzyw"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/camwhores"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/cavporn"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/chatwhores"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/clips4sale"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/cuinc"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/dlsite"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/dmm-porn"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/dmm"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/ehentai"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/erolabs"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/fans66"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/fansta"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/hentaivn"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/heyzo"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/hooligapps"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/illusion"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/illusion-nonofficial"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/jable"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/javbus"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/javcc"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/javdb"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/japonx"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/javwide"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/jkf"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/johren"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/justav"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/kemono"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/konachan"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/kubakuba"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/lethalhardcore"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/lisiku"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/metart"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/mindgeek-porn"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/moxing"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/netflav"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/nudevista"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/picacg"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/playboy"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/pornpros"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/sehuatang"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/shireyishunjian"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/smtiaojiaoshi"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/spankbang"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/swag"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/theporndude"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/thescoregroup"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/tokyo-toshokan"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/truyen-hentai"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/uu-chat"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/xhamster"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/xingkongwuxianmedia"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/xnxx"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/xvideos"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/youjizz"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/yunlaopo"
          "https://raw.githubusercontent.com/v2fly/domain-list-community/master/data/zhimeishe"
        )
        for url in "${links[@]}"; do
          filename=$(basename "$url")
          curl -o "download/$filename" "$url"
        done

    - name: Merge files
      run: cat download/* > merged.txt

    - name: Remove lines starting with 'include:'
      run: grep -v '^include:' merged.txt > no_includes.txt

    - name: Sort and remove duplicate domains
      run: sort no_includes.txt | uniq > unique_domains.txt

    - name: Save final merged file
      run: mv unique_domains.txt merged.txt

    - name: Commit and Push
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add merged.txt
        git commit -m 'Add merged domain list'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
